### ISSUE TITLE
Topology view stops working after a few days

### ISSUE THREAD

**Issue by sdodson** [netobserv/network-observability-operator#106]
In a relatively small test cluster it's been observed that the topology view stops working a few days after installation utilizing the default configuration, with the following error message on the console. While this is tunable by adjusting the limits config it seems like this default should be increased to accommodate slightly larger topologies out of the box.

```
Error: Request failed with status code 400 Message: Error while fetching flows from Loki: Loki backend responded: Unknown error from Loki - cannot unmarshal (code: 400 resp: maximum of series (500) reached for a single query )
```

**Comment by jotak** [comment]
@jpinsonneau is there something we can do to still display up to that maximum of series, as a kind of degraded mode?
For my understanding, is this limit of series related to our "limit" setting, or is it different things?

**Comment by jotak** [comment]
PS: some related UI improvement tracked in JIRA: https://issues.redhat.com/browse/NETOBSERV-372

**Comment by jpinsonneau** [comment]
@jotak as soon as a limit is exceeded, the Loki query fails. You can't get results without modifying the query / limits.

Our [current config](https://raw.githubusercontent.com/netobserv/documents/main/examples/zero-click-loki/2-loki.yaml) doesn't contains limits, so the defaults are taken. We need to add at least in this case:
```
limits_config:  
   max_query_series: <LIMIT_TO_DEFINE>
```
We should probably increase other limits to avoid similar issues but keep in mind that this Loki deployment is **not for production purpose**.

An additional improvement could be to reduce [the step](https://github.com/netobserv/network-observability-console-plugin/blob/main/pkg/loki/topology_query.go#L155) according to selected `TimeRange`. It is currently forced to `60s` whatever range is selected. This will reduce the number of queries for large range.

At the end I'm more in favor to let the user be aware of limitations since these will depend of it's configuration and the size of the cluster.

**Comment by jotak** [comment]
Thanks Julien
Another question: would adding more filters (e.g. namespace filters), to narrow down the query search, be a valid workaround to avoid this error?

**Comment by jpinsonneau** [comment]
Improved frontend error messages https://github.com/netobserv/network-observability-console-plugin/pull/171
