### ISSUE TITLE
Unable to get overview, flows, topology 

### ISSUE THREAD

**Issue by jon2100** [netobserv/network-observability-operator#330]
I installed it using the "For a quick try that is not suitable for production and not scalable" method from the operator hub; after I got the storage sorted out, everything came up and is running, but I have this error: " Error: Request failed with status code 401
user not in cluster-admins group" on all views under Network Traffic, and the user I am logged into the cluster with is definitely in the cluster-admins group, and I can not find anything with a "user" for me to add or create.

**Comment by jotak** [comment]
Hi @jon2100 thanks for reporting this issue.
We're already aware of the problem, this is tracked here as well: https://issues.redhat.com/browse/NETOBSERV-972 . It will be fixed in the next release (by the way, can you provide the version of netobserv you installed?)

As a workaround, you should be able to get it work by setting `spec.loki.authToken` to `FORWARD` in the FlowCollector resource. In this mode, the logged in user token will be passed to Loki for queries - since you use our quick-install loki setup, it will just be ignored, but since we have more relaxed checks in this mode (we just check that it's a valid user token - not necessarily an admin), you will be able to get the flows.

Just be aware that it means any valid user could potentially get the flows. If you need to secure user access, you should rather the loki-operator, which will authorize the queries as appropriate.

**Comment by jon2100** [comment]
Thanks for the reply, I will give the workaround a shot.
The version of the operator is 1.2 that I am running on a 4.12 cluster

**Comment by jotak** [comment]
This will be fixed via https://github.com/netobserv/network-observability-console-plugin/pull/326 - pending release
